import type { PartInfo } from '../../core/types';
export type { PartInfo };

type Side = 'port' | 'starboard';
const SIDES: Side[] = ['port', 'starboard'];
const cap = (s: string) => s[0].toUpperCase() + s.slice(1);
const hand = (s: Side) => (s === 'port' ? 'left' : 'right');

function paired(
  make: (side: Side) => Omit<PartInfo, 'id' | 'name'> & { base: string; label: string },
): PartInfo[] {
  return SIDES.map((side) => {
    const { base, label, aliases = [], ...rest } = make(side);
    return {
      id: `${base}-${side}`,
      name: `${cap(side)} ${label}`,
      aliases: [...aliases, `${hand(side)} ${label.toLowerCase()}`],
      ...rest,
    };
  });
}

const EXTERIOR: PartInfo[] = [
  { id: 'radome', name: 'Radome / Nose Cone', group: 'exterior', category: 'Airframe', aliases: ['nose cone', 'nose', 'radar dome'],
    description: 'Pointed radar-transparent nose. In Battroid it telescopes back over the nose barrel and points down between the thighs.' },
  { id: 'forward-fuselage', name: 'Forward Fuselage', group: 'exterior', category: 'Airframe', aliases: ['cockpit section', 'nose section'],
    description: 'Cockpit section with the black anti-glare band and the vermilion side stripe carrying the U.N. Spacy roundel. Folds 180° onto the chest.' },
  { id: 'canopy', name: 'Cockpit Canopy', group: 'exterior', category: 'Airframe', aliases: ['windshield', 'windscreen', 'cockpit glass'],
    description: 'Green-tinted bubble canopy. In Battroid it faces forward from the middle of the chest.' },
  { id: 'chest-plate', name: 'Chest Plate', group: 'exterior', category: 'Armor', aliases: ['chest', 'dorsal hatch', 'cockpit hatch'],
    description: 'Dorsal section behind the canopy: a spine that carries the canopy line aft and ramps down to the fuselage, flanked by lower sides over the intakes that slope down outboard, with Hikaru’s vermilion chevrons and black vents. When the nose section folds down it becomes the upper chest, the spine its raised centre panel.' },
  { id: 'airbrake', name: 'Dorsal Airbrake', group: 'exterior', category: 'Flight surfaces', aliases: ['speed brake', 'air brake', 'speedbrake'],
    description: 'The VF-1’s large airbrake directly behind the canopy: hinged at its forward edge, it opens 60° to add drag, turned in its hinge line by rotary actuators either side of the canopy shield’s stowage (the hoods stow right under it, so there is no room for a strut). It has three black “no step” slats and sits in the centre of the Battroid chest.' },
  { id: 'chest-lights', name: 'Chest Floodlights', group: 'exterior', category: 'Sensors', aliases: ['shoulder lights', 'amber lights', 'searchlights'],
    description: 'Twin amber floodlights on the rear bulkhead of the nose section, facing up beside the head in Battroid.' },
  { id: 'center-fuselage', name: 'Centre Fuselage', group: 'exterior', category: 'Airframe', aliases: ['torso', 'body', 'main fuselage'],
    description: 'Main structural body: the fighter’s mid-section and the Battroid torso. A full-width dorsal skin over the wing gloves sits on a ±0.9 m keel that the engine nacelles tuck in beside.' },
  { id: 'waist-keel', name: 'Waist Keel', group: 'exterior', category: 'Airframe', aliases: ['waist', 'hips'],
    description: 'Narrow waist at the base of the torso. In flight the tail module’s front channel straddles it; in Battroid it is the waist between the chest and the hips.' },
  { id: 'arm-bay', name: 'Ventral Arm Bay', group: 'exterior', category: 'Airframe', aliases: ['belly', 'underside'],
    description: 'Navy-lined recess under the centre fuselage where both arms lie between the engines in Fighter mode.' },
  { id: 'dorsal-hatch', name: 'Dorsal Access Hatch', group: 'exterior', category: 'Airframe', aliases: ['spine hatch', 'access panel'],
    description: 'Maintenance hatch over the power core and avionics wiring on the fighter’s spine.' },
  ...paired((s) => ({ base: 'glove', label: 'Wing Glove', group: 'exterior', category: 'Flight surfaces', aliases: ['strake', 'wing root'],
    description: `Fixed ${s} strake with a vermilion leading edge, housing the swing-wing pivot bearing.` })),
  ...paired((s) => ({ base: 'wing', label: 'Main Wing', group: 'exterior', category: 'Flight surfaces', aliases: ['wing', 'swing wing'],
    description: `Variable-geometry ${s} wing: a NACA-section wing box that sweeps from 20° to 72° in flight (scheduled with Mach like the F-14’s) and to 90° to stow in Battroid. It carries two swivelling hardpoints, a vermilion stripe and the U.N. Spacy roundel.` })),
  ...paired((s) => ({ base: 'wing-slat', label: 'Leading-Edge Slat', group: 'exterior', category: 'Flight surfaces', aliases: ['slat', 'leading edge slat', 'high lift'],
    description: `${cap(s)} leading-edge slat. It runs forward on its track and droops 20° at low speed or high angle of attack, adding lift and delaying the stall. Stowed above M0.9 or 50° sweep.` })),
  ...paired((s) => ({ base: 'wing-flap', label: 'Fowler Flap', group: 'exterior', category: 'Flight surfaces', aliases: ['flap', 'flaps', 'fowler flap', 'inboard flap'],
    description: `Inboard ${s} Fowler flap. It rolls aft on its tracks and drops 35°, adding wing area as well as camber for take-off and landing. Interlocked with the sweep (wings forward only), it blows back above 250 kt.` })),
  ...paired((s) => ({ base: 'wing-outer-flap', label: 'Two-Section Flap', group: 'exterior', category: 'Flight surfaces', aliases: ['flap', 'flaps', 'outboard flap', 'two-section flap'],
    description: `Outboard ${s} flap in two sections, hinged below its leading edge. Together with the Fowler flap it occupies almost the whole trailing edge, and it deflects 30°.` })),
  ...paired((s) => ({ base: 'wing-spoiler', label: 'Roll Spoiler', group: 'exterior', category: 'Flight surfaces', aliases: ['spoiler', 'spoilers', 'aileron', 'ailerons', 'roll control', 'spoileron'],
    description: `Upper-surface spoiler panels on the ${s} wing. The VF-1 has no ailerons: raising the spoiler on the down-going wing dumps its lift to roll the fighter, as on the F-14. They lock out above 57° sweep, where the wingtip thrusters take over.` })),
  ...paired((s) => ({ base: 'wingtip-rcs', label: 'Wingtip Roll Thrusters', group: 'exterior', category: 'Flight surfaces', aliases: ['rcs', 'roll thrusters', 'wingtip thrusters', 'reaction control', 'aileron', 'verniers'],
    description: `Wing thruster roll control system in the ${s} wingtip. Vernier ports above and below fire in opposite directions to roll the fighter, the only roll control at high sweep, at low speed and in space.` })),
  { id: 'tail-module', name: 'Tail Module / Backpack', group: 'exterior', category: 'Airframe', aliases: ['backpack', 'tail', 'rear fuselage'],
    description: 'Rear dorsal fuselage between the fins. In GERWALK the whole block rises past vertical as an airbrake and stands on the back leaning forward (GERWALK line art and kit): its aft vent grille faces forward, the red disc sits on top, the vernier cluster faces up and aft, and the antenna boom stands vertical with its whip out. The fins lie folded flat at its base. In Battroid it rides up between the shoulder blades as the backpack.' },
  { id: 'tail-thrusters', name: 'Backpack Vernier Ports', group: 'exterior', category: 'Propulsion', aliases: ['backpack thrusters', 'verniers', 'exhaust grille'],
    description: 'Three-nozzle vernier cluster on the tail module’s belly, under the red disc. It faces up and aft from the GERWALK block on the back, and rearward from the Battroid backpack.' },
  { id: 'nose-gear', name: 'Nose Landing Gear', group: 'exterior', category: 'Landing gear', aliases: ['nose gear', 'front wheel', 'landing gear', 'undercarriage', 'nose wheel'], stowedIn: ['gerwalk', 'battroid'],
    description: 'Twin-wheel nose gear under the cockpit: oleo strut, steering collar, torque links and a landing light. It swings forward into a bay under the cockpit floor for flight and before every conversion.' },
  { id: 'nose-gear-doors', name: 'Nose-Gear Doors', group: 'exterior', category: 'Landing gear', aliases: ['gear doors', 'wheel well doors'],
    description: 'Pair of doors in the cockpit belly that open before the nose gear drops and close only once it is home.' },
  ...paired((s) => ({ base: 'main-gear', label: 'Main Landing Gear', group: 'exterior', category: 'Landing gear', aliases: ['main gear', 'main wheel', 'landing gear', 'undercarriage'], stowedIn: ['gerwalk', 'battroid'],
    description: `Single-wheel main gear under the ${s} engine nacelle (about 9.7 m aft of the nose tip). It folds aft into a bay in the shin.` })),
  { id: 'tail-antenna', name: 'Antenna Boom', group: 'exterior', category: 'Sensors', aliases: ['antenna', 'whip antenna', 'mast', 'boom'],
    description: 'Antenna boom off the tail module’s aft face, the thin boom behind the fins in the five-view. In GERWALK it swings up from the flipped block’s leading end and a whip antenna telescopes out of it; in Battroid it retracts into the backpack.' },
  ...paired((s) => ({ base: 'tail-fin', label: 'Tail Fin', group: 'exterior', category: 'Flight surfaces', aliases: ['vertical stabilizer', 'fin', 'tail fin'],
    description: `${cap(s)} vertical stabiliser, canted 22.5° outboard, with Hikaru’s vermilion stripe. It folds flat on the hinge barrel along its root before the back block rises in GERWALK (transformation sheet), pitching on a boss at the block’s edge so it stays flat as the block stands; in Battroid it drops to the backpack’s outer face, spread behind the shoulder.` })),
  ...paired((s) => ({ base: 'rudder', label: 'Rudder', group: 'exterior', category: 'Flight surfaces', aliases: ['rudder', 'rudders', 'yaw control'],
    description: `Honeycomb-construction rudder on the ${s} fin, ±25° for yaw control. Both rudders deflect together.` })),
  { id: 'head-unit', name: 'Head Unit', group: 'exterior', category: 'Sensors', aliases: ['head', 'laser turret', 'sensor head'], stowedIn: ['fighter', 'gerwalk'],
    description: 'VF-1J helmet: the visor under its brow, a V-shaped faceplate down to the chin, and the red crest stripe over the crown. In the air it doubles as a ventral laser turret. It rises from its bay behind the cockpit housing in Battroid.' },
  { id: 'sensor-visor', name: 'Sensor Visor', group: 'exterior', category: 'Sensors', aliases: ['visor', 'eye', 'camera'], stowedIn: ['fighter', 'gerwalk'],
    description: 'Green optical sensor visor that feeds the pilot’s Battroid-mode displays.' },
  { id: 'laser-cannons', name: 'Mauler RÖV-20 Laser Cannons', group: 'exterior', category: 'Weapons', aliases: ['lasers', 'head lasers', 'laser guns'], stowedIn: ['fighter', 'gerwalk'],
    description: 'Twin anti-aircraft laser barrels, which identify the J type (the A has one and the S has four). Stowed, they fold forward and down to hang in front of the cheek housings (clear of them) inside the head bay; they swing up over the chest once the head has risen.' },
  ...paired((s) => ({ base: 'shoulder', label: 'Shoulder Armor', group: 'exterior', category: 'Armor', aliases: ['shoulder', 'shoulder block'],
    description: `Boxy ${s} shoulder block, its front face carrying the red triangle that points outboard. It slides out from the arm bay to the side of the chest.` })),
  ...paired((s) => ({ base: 'upper-arm', label: 'Upper Arm', group: 'exterior', category: 'Armor', aliases: ['bicep', 'upper arm'],
    description: `${cap(s)} upper-arm segment between the shoulder joint and the elbow actuator.` })),
  ...paired((s) => ({ base: 'forearm', label: 'Forearm', group: 'exterior', category: 'Armor', aliases: ['forearm', 'lower arm'],
    description: `Heavy ${s} forearm with a black band. A thick outer shield with a red stripe rises past the elbow to a swept point. The hand retracts inside the forearm for flight.` })),
  ...paired((s) => ({ base: 'hand', label: 'Manipulator Hand', group: 'exterior', category: 'Armor', aliases: ['hand', 'fist', 'manipulator'], stowedIn: ['fighter'],
    description: `Five-fingered ${s} manipulator, retracted into the forearm in Fighter mode${s === 'starboard' ? '. It grips the GU-11 gun pod' : ''}.` })),
  { id: 'gun-pod', name: 'GU-11 Gun Pod', group: 'exterior', category: 'Weapons', aliases: ['gun', 'gunpod', 'rifle', 'cannon', 'gatling'],
    description: 'Howard GU-11 55 mm three-barrel Gatling pod with 200 rounds at 1,200 rds/min. Rides the ventral centreline in Fighter mode and stays attached to the right hand in all modes.' },
  ...paired((s) => ({ base: 'hip-joint', label: 'Hip Swing-Bar', group: 'exterior', category: 'Joints', aliases: ['hip joint', 'hip', 'swing bar'],
    description: `Navy ${s} hip carriage: a plate running on the hip rail, and the hub the leg turns on, between the rail and the intake’s inboard face (clear of the intake mouth and the air duct). The intake slides past the hub on its rack, from the lip in Fighter to the thigh in Battroid, and the carriage runs the whole leg from under the gloves to the waist.` })),
  ...paired((s) => ({ base: 'intake', label: 'Engine Intake', group: 'exterior', category: 'Propulsion', aliases: ['air intake', 'intake', 'inlet'],
    description: `Underslung ${s} intake box on top of the thigh: an F-14-style two-dimensional inlet, its upper (ramp-side) lip leading and the lower lip raked back. Inside, variable ramps under the upper wall, then a long diffuser to the fan face deep in the box. It faces forward in flight and shows its louvred shutters beside the nose in Battroid. A side cheek carries its outer flank down over the hip-swing joint; the hip hub’s rack runs along its inboard face.` })),
  ...paired((s) => ({ base: 'intake-ramps', label: 'Variable Intake Ramps', group: 'exterior', category: 'Propulsion', aliases: ['ramps', 'intake ramps', 'inlet ramps', 'variable ramps', 'f-14 ramps'],
    description: `Two ramps under the upper wall of the ${s} intake, as on the F-14’s inlet: ramp 1 hinged behind the lip, ramp 2 at the throat, meeting at their free edges. As the speed rises (the flight lab schedules them with the wing sweep) they lower to shape the shock pattern and slow the inflow to subsonic speed in the diffuser before the fan.` })),
  ...paired((s) => ({ base: 'bypass-door', label: 'Intake Bypass Door', group: 'exterior', category: 'Propulsion', aliases: ['bypass door', 'bleed door', 'spill door', 'inlet bypass'],
    description: `Door in the outboard wall of the ${s} intake, above the ramps’ throat. At high speed it swings out to spill the air the engine cannot take (the F-14 inlet’s bypass).` })),
  ...paired((s) => ({ base: 'thigh', label: 'Thigh Nacelle', group: 'exterior', category: 'Armor', aliases: ['thigh', 'upper leg'],
    description: `Short ${s} thigh below the hip, carrying the ${s === 'port' ? 'red' : 'blue'} navigation light. Full-height side walls keep the nacelle unbroken from the side; behind them the lower back is cut away so the shin can flex back at the knee.` })),
  ...paired((s) => ({ base: 'knee-joint', label: 'Knee Joint Housing', group: 'exterior', category: 'Joints', aliases: ['knee'],
    description: `${cap(s)} knee hinge on the leg’s front face under a white knee cap. The shin swings 90° forward-down on it to hang below the level thigh in GERWALK, and flexes back in Battroid.` })),
  ...paired((s) => ({ base: 'shin', label: 'Shin Armor / Engine Nacelle', group: 'exterior', category: 'Armor', aliases: ['shin', 'lower leg', 'nacelle', 'engine nacelle', 'shin armor'],
    description: `${cap(s)} engine nacelle with the vermilion calf band, red-tipped leg fin and U.N. Spacy lettering. Below the knee the calf bulges outboard around the reaction turbine; in Fighter mode it is the rounded rear of the nacelle.` })),
  ...paired((s) => ({ base: 'ankle-joint', label: 'Ankle Ball Joint & Gimbal', group: 'exterior', category: 'Joints', aliases: ['ankle', 'ankle gimbal', 'ball joint', 'swivel bearing'],
    description: `Spherical bearing at the bottom of the ${s} shin, with a gimbal ring and trunnions. The exhaust passes through the ball, so the nozzle can pitch and roll to keep the foot level without the duct leaking or fouling the shin. The nozzle body fits over the duct below it.` })),
  ...paired((s) => ({ base: 'foot', label: 'Foot / 2-D Nozzle Body', group: 'exterior', category: 'Propulsion', aliases: ['foot', 'nozzle', 'exhaust', 'boot'],
    description: `Convergent section of the ${s} engine's two-dimensional nozzle, in line with the shin on the ankle ball joint. The throat is the slot between the flap roots under its end, closed at the sides by the clevis walls that carry the flap pins. Standing, the exhaust fires straight down through the slot between the toe and heel.` })),
  ...paired((s) => ({ base: 'foot-toe', label: 'Toe (Lower Nozzle Flap)', group: 'exterior', category: 'Propulsion', aliases: ['toe', 'toe flap', 'lower nozzle flap', 'nozzle flap', 'elevator', 'pitch control', 'thrust vectoring'],
    description: `Front half of the ${s} split nozzle. In flight it is the lower divergent flap, vectoring with the heel in place of elevators (Macross Compendium). For GERWALK and Battroid it swings 80° forward: its inner face becomes the sole and its tapered outer face the sloping top of the toe.` })),
  ...paired((s) => ({ base: 'foot-heel', label: 'Heel (Upper Nozzle Flap)', group: 'exterior', category: 'Propulsion', aliases: ['heel', 'heel flap', 'upper nozzle flap', 'nozzle flap', 'thrust vectoring'],
    description: `Back half of the ${s} split nozzle. In flight it is the upper divergent flap; on the ground it swings 80° back to form the heel. While skimming in GERWALK the toe and heel close part-way to vector the jets down and aft.` })),
  { id: 'canopy-shield', name: 'Armoured Canopy Shield', group: 'exterior', category: 'Cockpit', aliases: ['canopy shield', 'canopy cover', 'heat shield', 'armoured canopy cover'],
    description: 'Retractable armoured cover for the canopy (Macross Compendium: for Battroid mode and atmospheric reentry). Two nested hoods stow in the chest spine behind the canopy. During the Battroid conversion they run forward on rails recessed in the canopy sills, the front hood telescoping out of the rear one, before the cockpit retracts into the chest.' },
  ...paired((s) => ({ base: 'shoulder-lock', label: 'Shoulder Lock', group: 'exterior', category: 'Joints', aliases: ['shoulder lock', 'shoulder saddle', 'arm lock', 'shoulder mount'],
    description: `Saddle that runs out of the back of the ${s} shoulder block and clamps into the glove, holding the arm's carriage to the airframe in GERWALK and Battroid. It retracts into the block when the arm stows for flight.` })),
  ...paired((s) => ({ base: 'hip-lock', label: 'Hip Swing-Bar Lock', group: 'exterior', category: 'Joints', aliases: ['hip lock', 'swing bar', 'leg mount', 'hip mount'],
    description: `Arm of the ${s} hip carriage that reaches into the fuselage side in Fighter and GERWALK, holding the leg to the airframe. It folds up into the intake before the carriage runs down the torso for Battroid.` })),
  ...paired((s) => ({ base: 'hip-rail', label: 'Hip Rail', group: 'exterior', category: 'Joints', aliases: ['hip rail', 'rails', 'leg rail', 'hip track', 'splitter'],
    description: `Track the ${s} hip carriage runs on between the Fighter mount beside the intake mouth and the Battroid hip below the waist: a chest section on the chest plate's keel (its web is the intake's boundary-layer splitter), a fixed section along the torso, and a lower section that telescopes out below the waist for Battroid.` })),
  ...paired((s) => ({ base: 'leg-vernier', label: 'Counter-Reverse Vernier', group: 'exterior', category: 'Propulsion', aliases: ['vernier', 'reverse thruster', 'leg thruster', 'intake vernier'],
    description: `High-thrust counter-reverse vernier nozzle on the outer side of the ${s} intake (Macross Compendium: one per leg nacelle). It fires forward to brake and to back away.` })),
  ...paired((s) => ({ base: 'calf-vernier', label: 'Aft Nacelle Verniers', group: 'exterior', category: 'Propulsion', aliases: ['vernier', 'calf thruster', 'leg thrusters', 'rear verniers'],
    description: `Pair of vernier ports low on the back of the ${s} calf, part of the aft-nacelle vernier system (Macross Compendium). They trim attitude in GERWALK and Battroid.` })),
];

const INTERNAL: PartInfo[] = [
  // engines
  ...paired((s) => ({ base: 'turbine', label: 'Turbine', group: 'internal', system: 'engines', category: 'Engines', aliases: ['ff-2001', 'engine', 'turbine core', 'thermonuclear turbine', 'turbine blades'],
    description: `${cap(s)} Shinnakasu/P&W/Roice FF-2001 thermonuclear reaction turbine (11,500 kgf, 650 MW) in the shin. Its three-stage turbine on the high-pressure spool drives the compressor through the central shaft. In the flight lab it spins with the throttle.` })),
  ...paired((s) => ({ base: 'fan', label: 'Intake Fan', group: 'internal', system: 'engines', category: 'Engines', aliases: ['fan', 'fan blades', 'inlet guide vanes', 'n1'],
    description: `Inlet guide vanes and a two-stage fan behind the ${s} intake face, on the low-pressure (N1) spool with a chrome spinner.` })),
  ...paired((s) => ({ base: 'compressor', label: 'Axial Compressor', group: 'internal', system: 'engines', category: 'Engines', aliases: ['compressor', 'compressor stages', 'n2', 'core'],
    description: `Five-stage axial compressor on the ${s} high-pressure (N2) spool. It squeezes the intake air before the reaction chamber and turns about 1.6 times faster than the fan.` })),
  ...paired((s) => ({ base: 'reaction-chamber', label: 'Thermonuclear Reaction Chamber', group: 'internal', system: 'engines', category: 'Engines', aliases: ['reactor', 'fusion reactor', 'combustor', 'reaction chamber', 'burner'],
    description: `Where a jet would burn fuel, the ${s} FF-2001 heats the compressed air with a thermonuclear reactor, so there is no fuel limit in the atmosphere. The annulus glows brighter with throttle.` })),
  ...paired((s) => ({ base: 'intake-duct', label: 'Intake Duct', group: 'internal', system: 'engines', category: 'Engines', aliases: ['duct', 'air duct'],
    description: `${cap(s)} air duct, unbroken from the fan to the compressor: down the intake, through a ball swivel on the hip-swing pivot, along the thigh to the knee bellows, then the shin’s inlet cone.` })),
  ...paired((s) => ({ base: 'duct-bellows', label: 'Knee Duct Bellows', group: 'internal', system: 'engines', category: 'Engines', aliases: ['bellows', 'knee duct', 'flexible duct'],
    description: `Corrugated ${s} bellows that carries the engine air round the knee, from the thigh duct into the engine’s inlet through the opening in the top of the shin. Its sleeves share out the knee’s bend on an arc about the hinge: a straight run in Fighter mode, a right angle in GERWALK, where it shows between the thigh and the shin.` })),
  // nozzles
  ...paired((s) => ({ base: 'exhaust-duct', label: 'Exhaust Duct', group: 'internal', system: 'engines', category: 'Engines', aliases: ['tailpipe', 'exhaust duct', 'jet pipe'],
    description: `${cap(s)} tailpipe from the turbine casing down the lower shin to the ankle's ball joint, easing onto the nozzle axis so the hot stream runs unbroken into the split nozzle.` })),
  ...paired((s) => ({ base: 'nozzle', label: 'Thrust-Vectoring Nozzle', group: 'internal', system: 'nozzles', category: 'Thrust vectoring', aliases: ['vectoring nozzle', 'nozzle', 'exhaust nozzle', 'thrust vectoring'],
    description: `${cap(s)} split nozzle's convergent section: the flared duct from the ankle ball joint, the petals that squeeze the flow into the throat slot, and the throat's glow. The toe and heel flaps outside form the divergent section.` })),
  // avionics
  { id: 'radar-array', name: 'Forward Radar Array', group: 'internal', system: 'avionics', category: 'Avionics', aliases: ['radar', 'antenna', 'fire control radar'],
    description: 'Fire-control radar antenna and transceiver packed inside the radome.' },
  { id: 'avionics-bay', name: 'Avionics Bay', group: 'internal', system: 'avionics', category: 'Avionics', aliases: ['avionics', 'computers', 'electronics bay'],
    description: 'Flight-control and transformation-sequencing computers stacked behind the cockpit.' },
  { id: 'head-sensor-cluster', name: 'Head Sensor Cluster', group: 'internal', system: 'avionics', category: 'Avionics', aliases: ['sensor cluster', 'cameras', 'optics'], stowedIn: ['fighter', 'gerwalk'],
    description: 'Optical, IR and laser-ranging sensors behind the visor. They drive the Battroid monitors.' },
  // cockpit
  { id: 'cockpit-capsule', name: 'Cockpit Capsule', group: 'internal', system: 'cockpit', category: 'Cockpit', aliases: ['cockpit', 'capsule', 'survival cell'],
    description: 'Armoured survival cell that stays pilot-upright while the nose section folds around it.' },
  { id: 'ejection-seat', name: 'Ejection Seat & Pilot', group: 'internal', system: 'cockpit', category: 'Cockpit', aliases: ['seat', 'pilot', 'hikaru'],
    description: 'Zero-zero ejection seat with Lt. Hikaru Ichijyo in his flight suit.' },
  { id: 'hud-console', name: 'HUD & Instrument Console', group: 'internal', system: 'cockpit', category: 'Cockpit', aliases: ['hud', 'instruments', 'controls', 'console'],
    description: 'Head-up display and mode-select controls: the Fighter / GERWALK / Battroid lever sits by the left hand.' },
  // actuators
  ...paired((s) => ({ base: 'knee-gearbox', label: 'Knee Gear Set', group: 'internal', system: 'actuators', category: 'Joint drives', aliases: ['knee gears', 'knee gearbox', 'rotary actuator'],
    description: `${cap(s)} knee drive. A ring of gears fixed to the shin turns about the hinge while the thigh-mounted pinions spin 2.4× faster to follow it. It works alongside the hydraulic ram.` })),
  ...paired((s) => ({ base: 'ankle-gearbox', label: 'Ankle Gear Set', group: 'internal', system: 'actuators', category: 'Joint drives', aliases: ['ankle gears', 'ankle gearbox'],
    description: `${cap(s)} ankle pitch drive on the gimbal trunnions. It works with the ankle rams to keep the nozzle upright on uneven ground.` })),
  ...paired((s) => ({ base: 'shoulder-drive', label: 'Shoulder Drives', group: 'internal', system: 'actuators', category: 'Joint drives', aliases: ['shoulder motor', 'shoulder actuator', 'shoulder gears', 'harmonic drive', 'servo'],
    description: `One drive per axis of the ${s} shoulder: a gear set on the pitch pivot (the pinion in the shoulder block follows the arm at 2.7:1), a servo pack for raising the arm out, a slewing ring for upper-arm twist, and a servo in the block that rocks it.` })),
  ...paired((s) => ({ base: 'wrist-drive', label: 'Wrist Drives', group: 'internal', system: 'actuators', category: 'Joint drives', aliases: ['wrist motor', 'wrist actuator', 'wrist servo'],
    description: `Servo pack for the ${s} wrist bend and a slewing ring that twists the hand.` })),
  ...paired((s) => ({ base: 'hip-drive', label: 'Hip Drives', group: 'internal', system: 'actuators', category: 'Joint drives', aliases: ['hip motor', 'hip gears', 'hip servo', 'hip actuator'],
    description: `Walking-hip gear set on the ${s} thigh trunnions (the pinion in the intake box follows the stride); on the swing-bar hip, a pitch gear set on the hub (its pinion in the carriage), a servo pack for spreading the leg and a slewing ring for twisting it.` })),
  ...paired((s) => ({ base: 'ramp-actuator', label: 'Intake Ramp Rams', group: 'internal', system: 'actuators', category: 'Actuators', aliases: ['ramp actuator', 'ramp rams', 'inlet actuators'],
    description: `Two small rams in the bay between the upper wall of the ${s} intake and its ramps, which set each ramp for the speed.` })),
  { id: 'head-drives', name: 'Head Turret Drives', group: 'internal', system: 'actuators', category: 'Joint drives', aliases: ['neck', 'turret ring', 'head motor', 'laser servo'],
    description: 'Slewing ring that turns the head turret, a servo that nods it, and small servos that elevate the twin lasers.' },
  ...paired((s) => ({ base: 'ankle-actuator', label: 'Ankle Rams', group: 'internal', system: 'actuators', category: 'Actuators', aliases: ['ankle actuator', 'ankle rams', 'nozzle actuator'],
    description: `Two exposed hydraulic rams between the ${s} ankle collar and the nozzle body’s shoulder, outboard of the ball joint and its gimbal ring, one in front for pitch and one behind for roll. They tilt the nozzle on its ball joint.` })),
  ...paired((s) => ({ base: 'toe-actuator', label: 'Toe Flap Ram', group: 'internal', system: 'actuators', category: 'Actuators', aliases: ['toe actuator', 'nozzle flap actuator'],
    description: `Ram inside the ${s} nozzle body that swings the toe flap between the divergent-flap position and the flat toe.` })),
  ...paired((s) => ({ base: 'heel-actuator', label: 'Heel Flap Ram', group: 'internal', system: 'actuators', category: 'Actuators', aliases: ['heel actuator', 'nozzle flap actuator'],
    description: `Ram inside the ${s} nozzle body that swings the heel flap between the divergent-flap position and the flat heel.` })),
  ...paired((s) => ({ base: 'elbow-gearbox', label: 'Elbow Gear Set', group: 'internal', system: 'actuators', category: 'Joint drives', aliases: ['elbow gears', 'elbow gearbox'],
    description: `Gear and pinion pair in the ${s} elbow that bends the forearm. The pinion follows the joint at 2.4:1.` })),
  ...paired((s) => ({ base: 'wing-pivot-drive', label: 'Wing Pivot Drive', group: 'internal', system: 'actuators', category: 'Joint drives', aliases: ['wing pivot', 'sweep gear', 'slewing ring'],
    description: `Slewing ring gear at the ${s} wing pivot, driven by a pinion in the glove. It turns with the sweep, from 20° through 72° in flight to the Battroid stowage position past vertical.` })),
  ...paired((s) => ({ base: 'knee-actuator', label: 'Hydraulic Knee Actuator', group: 'internal', system: 'actuators', category: 'Actuators', aliases: ['knee actuator', 'knee piston', 'hydraulic knee'],
    description: `Four-stage hydraulic ram across the front of the ${s} knee, from the knee housing below the thigh casing down inside the shin. It swings the shin through 90° for GERWALK and still reaches when the knee flexes back in Battroid.` })),
  ...paired((s) => ({ base: 'elbow-actuator', label: 'Elbow Actuator', group: 'internal', system: 'actuators', category: 'Actuators', aliases: ['elbow piston', 'elbow'],
    description: `Hydraulic ram behind the ${s} elbow hinge, beside the arm frame: it stretches as the forearm bends forward.` })),
  ...paired((s) => ({ base: 'wing-actuator', label: 'Wing-Sweep Actuator', group: 'internal', system: 'actuators', category: 'Actuators', aliases: ['sweep actuator', 'wing actuator'],
    description: `Screw-jack in the ${s} glove that sweeps the wing from 20° to the 90° stow position.` })),
  ...paired((s) => ({ base: 'wing-swing-arm', label: 'Wing-Root Swing Arm', group: 'internal', system: 'actuators', category: 'Actuators', aliases: ['wing arm', 'wing root arm', 'swing arm', 'parallel link', 'wing carriage'],
    description: `Parallel pair of links hinged in the ${s} glove that carries the wing-root carriage for Battroid: one 147° swing lifts it straight up out of the glove, over, and down onto the back beside the backpack, the wing keeping its attitude all the way.` })),
  ...paired((s) => ({ base: 'arm-transfer', label: 'Shoulder Transfer Arm', group: 'internal', system: 'actuators', category: 'Actuators', aliases: ['transfer arm', 'arm slider', 'shoulder carrier', 'arm carrier'],
    description: `Folding two-link arm hinged under the ${s} glove's trailing edge, outboard of the nacelle. Converting to GERWALK it reaches in behind the dropped leg, picks up the shoulder block by its socket once the block has slid aft out of the belly bay, carries it out and forward under the wing root, and folds away once the shoulder lock has clamped the block into the glove.` })),
  { id: 'gun-mount-strut', name: 'Gun-Pod Mount Strut', group: 'internal', system: 'actuators', category: 'Weapons', aliases: ['gun mount', 'gun pod mount', 'mount strut', 'pylon'],
    description: 'Six-stage telescopic strut from the starboard intake to a lug on the GU-11. It holds the pod on the ventral mount in flight, follows it as the mount runs it forward and down, swings it out under the intake (rolling it grip-up) into the right fist, and retracts once the fist has the grip.' },
  { id: 'neck-lift', name: 'Neck Lift Column', group: 'internal', system: 'actuators', category: 'Actuators', aliases: ['neck', 'head lift', 'neck column', 'head elevator'],
    description: "Three-stage telescopic column from the keel slab up through the head bay into the neck post, on the head's turn axis: it raises the head out of its bay for Battroid and lowers it for flight." },
  { id: 'nose-fold-actuator', name: 'Nose-Section Fold Actuator', group: 'internal', system: 'actuators', category: 'Actuators', aliases: ['nose actuator', 'fold actuator', 'chest hinge'],
    description: 'Paired three-stage rams that rotate the entire nose section 180° down onto the chest.' },
  { id: 'tail-fold-actuator', name: 'Tail-Module Fold Actuator', group: 'internal', system: 'actuators', category: 'Actuators', aliases: ['backpack actuator', 'tail actuator'],
    description: 'Three-stage support ram on the centre line, ahead of the stowed antenna boom, pinned to a clevis lug under the module: it lifts the tail module off the waist keel, flips it over the back (GERWALK) and holds it as the backpack (Battroid), passing between the stowed wings.' },
  // power
  { id: 'power-core', name: 'Main Power Core', group: 'internal', system: 'power', category: 'Power', aliases: ['power core', 'energy converter', 'core', 'generator'],
    description: 'Energy converter in the centre fuselage. It turns reactor output into electrical power for the actuators, lasers and avionics.' },
  { id: 'power-conduits', name: 'Power Conduits', group: 'internal', system: 'power', category: 'Power', aliases: ['conduits', 'power lines', 'cables'],
    description: 'Superconducting feed lines that run from the reactors up the swing-bars to the core.' },
  { id: 'capacitor-bank', name: 'Capacitor Bank', group: 'internal', system: 'power', category: 'Power', aliases: ['capacitors', 'battery'],
    description: 'Fast-discharge capacitor bank that buffers power for the laser cannons.' },
  // frame
  { id: 'spine-keel', name: 'Structural Spine', group: 'internal', system: 'frame', category: 'Frame', aliases: ['spine', 'keel', 'backbone', 'structural frame'],
    description: 'Box-section keel carrying flight loads in Fighter mode and body loads in Battroid.' },
  ...paired((s) => ({ base: 'leg-frame', label: 'Leg Load Frame', group: 'internal', system: 'frame', category: 'Frame', aliases: ['leg frame', 'leg strut'],
    description: `${cap(s)} load frame through the intake box, the shin and the ankle.` })),
  ...paired((s) => ({ base: 'arm-frame', label: 'Arm Load Frame', group: 'internal', system: 'frame', category: 'Frame', aliases: ['arm frame', 'arm strut'],
    description: `Internal ${s} arm skeleton that carries the manipulator loads.` })),
  // weapons
  { id: 'weapon-bay', name: 'Ventral Weapon Bay', group: 'internal', system: 'weapons', category: 'Weapons', aliases: ['weapon bay', 'gun mount', 'ventral turret'],
    description: 'Ventral hardpoint and feed coupling that carries the GU-11 on the centreline in flight.' },
  { id: 'gun-barrels', name: 'GU-11 Barrel Cluster', group: 'internal', system: 'weapons', category: 'Weapons', aliases: ['barrels', 'gatling barrels'],
    description: 'Three rotating 55 mm barrels with breech and drive motor.' },
  { id: 'ammo-drum', name: 'Ammunition Drum', group: 'internal', system: 'weapons', category: 'Weapons', aliases: ['ammo', 'magazine', 'drum'],
    description: 'Linkless 200-round drum for the GU-11.' },
  { id: 'ammo-feed', name: 'Ammo Feed Chute', group: 'internal', system: 'weapons', category: 'Weapons', aliases: ['feed', 'feed chute', 'ammo feed'],
    description: 'Flexible chute that feeds rounds from the drum to the breech.' },
  { id: 'laser-emitters', name: 'Laser Emitter Assemblies', group: 'internal', system: 'weapons', category: 'Weapons', aliases: ['emitters', 'laser core'], stowedIn: ['fighter', 'gerwalk'],
    description: 'Lasing chambers and cooling for the two Mauler RÖV-20 barrels.' },
];

export const PARTS: PartInfo[] = [...EXTERIOR, ...INTERNAL];
export const PART_BY_ID: Record<string, PartInfo> = Object.fromEntries(PARTS.map((p) => [p.id, p]));
