import { chromium } from '@playwright/test';
const browser = await chromium.launch({ channel: 'chrome', args: ['--ignore-gpu-blocklist', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: 800, height: 600 } });
const msgs = [];
page.on('console', (m) => msgs.push(`[${m.type()}] ${m.text()}`));
page.on('pageerror', (e) => msgs.push(`[pageerror] ${e.message}`));
await page.goto(process.argv[2] ?? 'http://localhost:4173');
await page.waitForFunction(() => window.__spike, null, { timeout: 20000 });
console.log('spike:', JSON.stringify(await page.evaluate(() => window.__spike)));
await page.waitForTimeout(500);
await page.screenshot({ path: 'shots/spike.png' });
console.log('console messages:', msgs.length ? msgs.join('\n') : '(none)');
await browser.close();
